config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # INDEX
  get "tasks", to: "tasks#index", as: "tasks"

  # NEW (http://localhost:3000/restaurants/new)
  get "/tasks/new", to: "tasks#new", as: "new_task"
  post "tasks", to: "tasks#create"

  # SHOW: (http://localhost:3000/tasks/3)
  get "/tasks/:id", to: "tasks#show", as: "task"

  #EDIT/UPDATE
  get "/tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "/tasks/:id", to: "tasks#update"

  #DELETE
  delete "/tasks/:id" , to: "tasks#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :details, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only:[:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def show
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: task do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :details %>
      <%= f.text_area :details, class: "form-control" %>
    </div>
    <% if show_completed %>
    <div class="form-group form-check">
      <%= f.check_box :completed, class: "form-check-input" %>
      <%= f.label :completed, class: "form-check-label" %>
    </div>
    <% end %>
    <%= f.submit task.new_record? ? "Create Task" : "Update Task", class: "btn btn-primary" %>
  <% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <h1>Updating task</h1>
  <%= render "form", task: @task, show_completed: true %>
  <%= link_to "Back", tasks_path %>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <h1 class="my-4">My Tasks</h1>
  <ul class="list-group">
    <% @tasks.each do |task| %>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <span>
          <%= task.completed ? '✅' : '⬜' %>
          <%= link_to task.title, task_path(task), class: "text-decoration-none"%>
        </span>
        <div>
          <%= link_to edit_task_path(task), class: "btn btn-warning btn-sm mr-2" do %>
            <i class="fas fa-edit"></i>
          <% end %>
          <%= link_to task_path(task), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
  <div class="mt-4">
    <%= link_to "New Task", new_task_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container mt-5">
  <h1 class="my-4">New Task</h1>
  <div class="card-body">
    <div class="row">
      <div class="col-md-6">
        <%= render "form", task: @task, show_completed: false %>
        <%= link_to "Back", tasks_path, class: "btn btn-secondary mt-3" %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <h1 class="my-4"><%= @task.title %></h1>
  <div class= "row mb-4">
    <div class="col-md-6">
      <h5><%= @task.details %></h5>
        <h6 class="text-muted">
          <%= check_box_tag 'completed', '1', @task.completed, disabled: true %> &nbsp; This task is <%= @task.completed ? 'completed' : 'not completed yet' %>
        </h6>
    </div>
    </div>
    <div class="mt-4">
      <%= link_to "Back", tasks_path, class: "btn btn-secondary" %>
      <%= link_to "Edit", edit_task_path(@task), class: "btn btn-primary" %>
    </div>
</div>